### ISSUE TITLE
Error in installing octave

### ISSUE THREAD

**Issue by guillempnadal** [dpo/homebrew-openblas#68] opened 2018-06-08 21:24 UTC
Hi, I am trying to install octave following the instructions in http://www.schoeps.org/home/2018/01/how-to-compile-gnu-octave-with-openblas-on-macos/
but I get the following errors:

Last 15 lines from /Users/guillem/Library/Logs/Homebrew/octave/03.make:
class QButtonGroup;
      ^
libgui/src/settings-dialog.cc:312:13: error: member access into incomplete type 'QButtonGroup'
  icon_group->addButton (ui->general_icon_letter);
            ^
/usr/local/Cellar/qt/5.11.0/include/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'QButtonGroup'
class QButtonGroup;
      ^
8 errors generated.
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I.   -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtNetwork -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtOpenGL -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtPrintSupport -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtWidgets -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtGui -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtCore -I/usr/local/Cellar/qt/5.11.0/include -I./libgui/qterminal/libqterminal -Ilibgui/src -I./libgui/src -I./libgui/src/m-editor -I./libgui/src/qtinfo -I./libgui/graphics -I./liboctave/array -Iliboctave/numeric -I./liboctave/numeric -Iliboctave/operators -I./liboctave/operators -I./liboctave/system -I./liboctave/util -Ilibinterp -I./libinterp -Ilibinterp/parse-tree -I./libinterp/parse-tree -Ilibinterp/corefcn -I./libinterp/corefcn -I./libinterp/octave-value -I./liboctave/wrappers  -fPIC -D_THREAD_SAFE -pthread -Wall -W -Wshadow -Wold-style-cast -Wformat -Wpointer-arith -Wwrite-strings -Wcast-align -Wcast-qual -I/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/include/darwin -c -o libgui/src/libgui_src_la-welcome-wizard.lo `test -f 'libgui/src/welcome-wizard.cc' || echo './'`libgui/src/welcome-wizard.cc
make[2]: *** [libgui/src/libgui_src_la-settings-dialog.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtNetwork -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtOpenGL -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtPrintSupport -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtWidgets -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtGui -I/usr/local/Cellar/qt/5.11.0/include -I/usr/local/Cellar/qt/5.11.0/include/QtCore -I/usr/local/Cellar/qt/5.11.0/include -I./libgui/qterminal/libqterminal -Ilibgui/src -I./libgui/src -I./libgui/src/m-editor -I./libgui/src/qtinfo -I./libgui/graphics -I./liboctave/array -Iliboctave/numeric -I./liboctave/numeric -Iliboctave/operators -I./liboctave/operators -I./liboctave/system -I./liboctave/util -Ilibinterp -I./libinterp -Ilibinterp/parse-tree -I./libinterp/parse-tree -Ilibinterp/corefcn -I./libinterp/corefcn -I./libinterp/octave-value -I./liboctave/wrappers -fPIC -D_THREAD_SAFE -pthread -Wall -W -Wshadow -Wold-style-cast -Wformat -Wpointer-arith -Wwrite-strings -Wcast-align -Wcast-qual -I/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/include/darwin -c libgui/src/welcome-wizard.cc  -fno-common -DPIC -o libgui/src/.libs/libgui_src_la-welcome-wizard.o
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Any ideas?

Thanks a lot!

**Comment by schoeps** [comment] 2018-06-09 10:33
Thabks for reporting. The problem is known and I made already a pull request with a fixed formula. If you want to use it know, you need to download it manually, see issue #67. Please report if it works (and close the issue if it is the case).

**Closed as completed** 2018-10-22 20:11 UTC
Labels: octave, build error
